server:
  port: 8086

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
  datasource:
    dataSourceClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tron_gym_db
    username: postgres
    password: postgres

security:
  ignored=/**: